### ISSUE TITLE
안녕하세요 TAM 잘 이용하고 있는 구독자 입니다.

### ISSUE THREAD

**Issue by pavk96** [LM-channel-team-project/Team-Auto-Matcher#103]
<img width="1440" alt="스크린샷 2021-08-11 오후 11 55 57" src="https://user-images.githubusercontent.com/56814290/129052630-23beac8b-fce6-4c77-922e-cbb16da238fc.png">
이 부분에서 확인 버튼에 기능이 아직 없는 것인가요?
혹시 하는 마음에 이슈 올려봅니다.

<img width="1440" alt="스크린샷 2021-08-11 오후 11 57 31" src="https://user-images.githubusercontent.com/56814290/129052905-6397d623-3590-4a98-ac69-9bf54dea1cac.png">
팀 현황판에서 제가 생성한 팀을 누르면 이렇게 아무것도 안 보이게 됩니다... 

바쁘신 와중에 죄송하지만 확인 좀 부탁드려도 될까요?

**Comment by Ho-s** [comment]
불편 드려 죄송합니다 ㅠㅡㅠ 메일에 있는 기능들  전부 구현했지만 에러인 것 같습니다 해결하고 빠르게 수정해드리도록하겠습니다!

**Comment by Ho-s** [comment]
아 팀 현황판에 팀 안보이시는 거는 일시적 오류입니다. 오늘 수정했으니 현황판은 잘 보실 수 있으실 겁니다! 메일 기능은 확인 후 다시 말씀 드리겠습니다.

**Comment by pavk96** [comment]
> 아 팀 현황판에 팀 안보이시는 거는 일시적 오류입니다. 오늘 수정했으니 현황판은 잘 보실 수 있으실 겁니다! 메일 기능은 확인 후 다시 말씀 드리겠습니다.

빠른 답변 감사드립니다

**Comment by pavk96** [comment]
정말 열심히 하셔서 저도 열심히하고 싶네요 화이팅입니다!

**Comment by Ho-s** [comment]
> 정말 열심히 하셔서 저도 열심히하고 싶네요 화이팅입니다!

사이트 통해서 좋은 팀프로젝트 진행하실 수 있게 노력하겠습니다! 감사합니다

**Comment by Ho-s** [comment]
> 정말 열심히 하셔서 저도 열심히하고 싶네요 화이팅입니다!

팀이 확인이 안된 건 일시적 오류였고, 수락도 정상적으로 작동되실겁니다! 또 오류 있으면 issue 남겨주시면 바로 수정해드리겠습니다!

**Comment by pavk96** [comment]
감사합니다.~
