### ISSUE TITLE
팀 대시보드 모달창 팀장 이름변경

### ISSUE THREAD

**Issue by lhk3337** [LM-channel-team-project/Team-Auto-Matcher#106]
- 팀을 새로 생성 하고 나서 모달창을 열어 보면 팀장 이름이 확인
- 창을 닫고 다시 모달 창을 클릭하면 팀이름이 나타납니다.
- 다시 새로 고침을 하면 팀장이름이 확인 됩니다.

<br />

![ezgif com-gif-maker](https://user-images.githubusercontent.com/44824320/129122701-ea465e6b-af27-436a-96e5-c63822a67392.gif)

**Comment by Ho-s** [comment]
팀 id와 자신의 id가 같아서 발생하는 오류
