### ISSUE TITLE
팀 깃헙 레퍼지토리 링크 추가

### ISSUE THREAD

**Issue by pkiop** [LM-channel-team-project/Team-Auto-Matcher#115]
레퍼지토리 링크 추가 하면 readme를 읽어와서 해당 프로젝트 정보를 팀 설명에 띄워주도록 구현

**Comment by pkiop** [comment]
![image](https://user-images.githubusercontent.com/34783156/129441830-7fbc5d54-efe8-48e8-ba45-64280e90104d.png)

**Comment by lhk3337** [comment]
이것을 구현 하려면 github API를 가져와서 처리해야 하나요?

**Comment by pkiop** [comment]
넵 가져와서 처리하면 됩니다!

**Comment by lhk3337** [comment]
현재 repository name을 입력하면 그 데이터를 dynamoDB에 저장하고 그것을 가져와 Teamdetail모달에 깃허브 api가 뜨도록 설정하였습니다.

**Comment by pkiop** [comment]
멋지네요!!
