### ISSUE TITLE
로그인 하고 설문 작성시 사진과 같은 모달 나오는 현상 수정

### ISSUE THREAD

**Issue by pkiop** [LM-channel-team-project/Team-Auto-Matcher#132]
![image](https://user-images.githubusercontent.com/34783156/130233578-0f4de066-7e4f-4216-b1c0-41950c33cfb2.png)

수정해서 안 나오게 하면 좋을 것 같습니다

**Comment by Ho-s** [comment]
withauthenticator 삭제
