### ISSUE TITLE
aws-exports 모듈을 찾을 수 없어 리액트 개발 서버를 실행하지 못합니다

### ISSUE THREAD

**Issue by youngrongoh** [LM-channel-team-project/Team-Auto-Matcher#14]
# 버그 문의

## 실행환경
MacOS Catalina 10.15.7 (19H15)
VScode 1.55.1
zsh 5.8 (x86_64-apple-darwin19.3.0)
node 12.19.0
npm 7.10.0
yarn 1.22.10

## 상세 내용

저장소를 클론하여 로컬에 받고,
`git clone https://github.com/LM-channel-team-project/Team-Auto-Matcher.git`
package-lock.json파일이 있기에 npm으로 패키지를 설치했습니다.
`npm i`

`/client/src/Apollo.ts` 파일에서 `aws-exports` 모듈이 없다고 에러가 표시됩니다.
`npm run start`를 하면 동일한 이유로 컴파일 단계에서 오류가 발생합니다.

yarn으로 해봐도 동일합니다😭

![image](https://user-images.githubusercontent.com/64844815/115006018-5bcf2900-9ee3-11eb-9aa4-e3a469ac0951.png)
![image](https://user-images.githubusercontent.com/64844815/115005821-3e01c400-9ee3-11eb-9250-288608ae0739.png)
![image](https://user-images.githubusercontent.com/64844815/115006060-65589100-9ee3-11eb-9898-787a3230765b.png)

**Comment by youngrongoh** [comment]
`.gitignore` 파일에 `src/aws-exports.js`이 추가되어 있었네요..!😅

**Comment by pkiop** [comment]
이거 설정 문서로 남겨서 README에 남겨뒀습니다! 좀 복잡하지만.. 안되면 연락주세요!
